### register
POST http://localhost:3001/users
Content-Type: application/json

{
    "username": "crart",
    "email": "test123@test.com",
    "password": "test",
    "role": "basic"
}


###
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

###
GET http://localhost:3001/userlist
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNjMyMzMwNTk5fQ.j1x-dGVaAfglDNuBDdnHLI6MQYBj5dZ1YOG_aQFvOmA"

###
GET http://localhost:3001/auto_login
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNjMyMzMwNTk5fQ.j1x-dGVaAfglDNuBDdnHLI6MQYBj5dZ1YOG_aQFvOmA"

###
DELETE http://localhost:3001/logout
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNjMyMzMwNTk5fQ.j1x-dGVaAfglDNuBDdnHLI6MQYBj5dZ1YOG_aQFvOmA"

###
POST http://localhost:3001/notes
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNjMyMzMwNTk5fQ.j1x-dGVaAfglDNuBDdnHLI6MQYBj5dZ1YOG_aQFvOmA"

{
    "title": "crart tips",
    "content": "On databases that support transactions with statements that change the schema, migrations are wrapped in a transaction. If the database does not support this then when a migration fails the parts of it that succeeded will not be rolled back. You will have to rollback the changes that were made by hand.",
    "tags": ["java", "javascript"]
}

###
GET http://localhost:3001/notes
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNjMyMzMwNTk5fQ.j1x-dGVaAfglDNuBDdnHLI6MQYBj5dZ1YOG_aQFvOmA"
###

###
GET http://localhost:3001/notes/1
Content-Type: application/json
###

GET http://localhost:3001/notelist
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwiZXhwIjoxNjMyMzMwNTk5fQ.j1x-dGVaAfglDNuBDdnHLI6MQYBj5dZ1YOG_aQFvOmA"

